"""Ask OpenRouter what is actually true, and write it to build/provider-truth.json.

Notebooks read that file. Nothing in this repo hardcodes a price, a context length or a
cache rule, because those are provider facts that change and differ per upstream model.
"""
from __future__ import annotations

import json
import os
import pathlib
import sys

import requests
from dotenv import load_dotenv

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "provider-truth.json"
BUDGET_OUT = ROOT / "build" / "budget.json"
BASE = "https://openrouter.ai/api/v1"
TIMEOUT = 30


def _key() -> str:
    load_dotenv(ROOT / ".env")
    key = os.getenv("OPENROUTER_API_KEY", "")
    if not key:
        sys.exit("OPENROUTER_API_KEY is not set. Run: make setup")
    return key


def fetch_models() -> list[dict]:
    r = requests.get(f"{BASE}/models", timeout=TIMEOUT)
    r.raise_for_status()
    return r.json()["data"]


def model_facts(models: list[dict], wanted: list[str]) -> dict[str, dict]:
    """Pull the facts we would otherwise be tempted to hardcode."""
    by_id = {m["id"]: m for m in models}
    facts = {}
    for name in wanted:
        m = by_id.get(name)
        if not m:
            continue
        pricing = m.get("pricing", {})
        facts[name] = {
            "context_length": m.get("context_length"),
            "prompt_usd_per_token": pricing.get("prompt"),
            "completion_usd_per_token": pricing.get("completion"),
            "supported_parameters": sorted(m.get("supported_parameters") or []),
        }
    return facts


def budget(key: str) -> dict:
    """Remaining credit. Shape only, never the key itself."""
    r = requests.get(f"{BASE}/key", headers={"Authorization": f"Bearer {key}"}, timeout=TIMEOUT)
    r.raise_for_status()
    d = r.json()["data"]
    return {
        "limit_usd": d.get("limit"),
        "usage_usd": d.get("usage"),
        "limit_remaining_usd": d.get("limit_remaining"),
    }


def wanted_models() -> list[str]:
    load_dotenv(ROOT / ".env")
    names = ("VAULT_MODEL", "VAULT_MODEL_REASONING", "VAULT_MODEL_SMALL")
    return [v for n in names if (v := os.getenv(n))]


def main() -> int:
    key = _key()
    models = fetch_models()
    wanted = wanted_models()
    truth = {
        "source": "https://openrouter.ai/api/v1/models",
        "note": "Generated by make probe. Never hand edit. Notebooks read this instead of "
                "hardcoding a price, a context length or a cache rule. Committed, so a "
                "clone with no key can still run every lesson.",
        "total_models_listed": len(models),
        "models": model_facts(models, wanted),
    }
    OUT.write_text(json.dumps(truth, indent=2) + "\n")

    # Account spend is nobody else's business, so it stays out of the repo.
    BUDGET_OUT.parent.mkdir(parents=True, exist_ok=True)
    BUDGET_OUT.write_text(json.dumps(budget(key), indent=2) + "\n")

    print(f"wrote {OUT.relative_to(ROOT)}")
    for name, f in truth["models"].items():
        print(f"  {name:34} ctx={f['context_length']} in={f['prompt_usd_per_token']}")
    print(f"  budget written to {BUDGET_OUT.relative_to(ROOT)}, which is not committed")
    missing = [m for m in wanted if m not in truth["models"]]
    if missing:
        print(f"\n  WARNING: not listed by the provider: {missing}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
